apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rkzl2nhbq-nodejs
  janus-idp.io/tekton: rkzl2nhbq-nodejs
  backstage.io/kubernetes-id: rkzl2nhbq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rkzl2nhbq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
